services:
  - type: web
    name: wheels-back
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/wheels-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DATABASE_URL
        value: url=jdbc:postgresql://localhost:5432/wheelsdb
      - key: DATABASE_USERNAME
        value: postgres
      - key: DATABASE_PASSWORD
        value: fuerzaaerea2
